## Create AWS EC2 Instance based on youtuber Yogesh Mehta

- hosts: localhost

  tasks:

    - name: Set up Security / Firewall Group
      ec2_group:
        name: lg_test_sg
        description: allow port 22 and 3389
        region: us-east-2c
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 142.131.15.48/32
          - proto: tcp
            from_port: 3389
            to_port: 3389
            cidr_ip: 142.131.15.48/32
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Provision EC2 Ubuntu instance
      ec2:
        key_name: lg_key
        region: us-east-2c
        instance_type: t2.micro
        image: ami-0f65671a86f061fcd
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          Name: test VM
          Owner: lgaudreau
        monitoring: no
        vpc_subnet_id: subnet-7f21ed33
        assign_public_ip: yes
        group: lg_test_sg
      register: ec2_out

    - name: wait for SSH
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ec2_out.instances}}'