## Create AWS EC2 Instance based on youtuber Yogesh Mehta

- hosts: localhost

  tasks:

    - name: Provision EC2 Ubuntu instance
      ec2:
        key_name: lg_key
        region: us-east-2
        instance_type: t2.micro
        image: ami-0f65671a86f061fcd
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          Name: test VM
          Owner: lgaudreau
        monitoring: no
        vpc_subnet_id: subnet-7f21ed33
        assign_public_ip: yes
        group: ansible_sg
      register: ec2_out

    - name: wait for SSH
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ec2_out.instances}}'